# Generated by Django 5.1 on 2025-06-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photologue", "0013_alter_watermark_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Name")),
                (
                    "slug",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="Slug"
                    ),
                ),
                ("added", models.DateField(auto_now_add=True, verbose_name="Added")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ("-added",),
            },
        ),
        migrations.CreateModel(
            name="PhotoExtended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="caption")),
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended",
                        to="photologue.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multilingual Caption",
                "verbose_name_plural": "Multilingual Captions",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.DateTimeField(verbose_name="Published")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Is public"),
                ),
                ("added", models.DateField(auto_now_add=True, verbose_name="Added")),
                ("modified", models.DateField(auto_now=True, verbose_name="Modified")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "slug",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="Slug"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_images",
                        to="photologue.photo",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="csnews_multilingual.tag"),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ("-published",),
                "get_latest_by": "published",
            },
        ),
    ]
