# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2026-06-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('csnews_multilingual', '0009_auto_20170216_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vertical_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_vertical_images', to='photologue.Photo'),
        ),
    ]
